services:
    Pbweb\AuditBundle\Service\AuditLog:
        arguments:
            - '@Symfony\Component\EventDispatcher\EventDispatcherInterface'

    Pbweb\AuditBundle\Service\AuditLogInterface: '@Pbweb\AuditBundle\Service\AuditLog'
    pbweb_audit.audit_log: '@Pbweb\AuditBundle\Service\AuditLog'
